---
#- name: deploy loki alerts
#  template:
#    src: "alert.rules.j2"
#    dest: "{{ loki_alerts_directory }}/ansible_managed.rules"
#    owner: "{{ loki_system_user }}"
#    group: "{{ loki_system_group }}"
#    mode: 0640
#    validate: "{{ _prometheus_binary_install_dir }}/promtool check rules %s"
#  when:
#    - loki_alert_rules != []
#  notify:
#    - restart loki

- name: Configure loki
  template:
    src: loki.yml.j2
    dest: /etc/loki.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart loki
