---
- include_tasks: 
    file: install.yml
    apply:
      tags:
        - loki
        - loki:install
        - install
  tags:
    - loki

- include_tasks: 
    file: config.yml
    apply:
      tags:
        - loki
        - loki:config
        - config
  tags:
    - loki
